Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 
   a,b,c,d: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   leia(a)
   leia(b)
   leia(c)
   d<-a+c-b
   escreva(d)

Fimalgoritmo