Algoritmo "60 por cento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2024
Var
// Seção de Declarações das variáveis 
   a: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   leia(a)
   escreva(a*0.6)
   

Fimalgoritmo